In [2]:
import torch

In [54]:
y = torch.rand(2, 3)

In [55]:
y

tensor([[0.0357, 0.1248, 0.0123],
        [0.7094, 0.5215, 0.5153]])

In [56]:
z = y.view(-1,2)

In [57]:
y[0, 1] = 0.4152

In [58]:
z

tensor([[0.0357, 0.4152],
        [0.0123, 0.7094],
        [0.5215, 0.5153]])

In [59]:
x = y.reshape(-1,2)
x[1,1] = 0.281
print(y)
print(x)

tensor([[0.0357, 0.4152, 0.0123],
        [0.2810, 0.5215, 0.5153]])
tensor([[0.0357, 0.4152],
        [0.0123, 0.2810],
        [0.5215, 0.5153]])


`reshape()` and `view()` share the memory. If you change the original data structure, the assigned variable value also changes.

In [60]:
a = torch.randn(1, 2, 3, 4)
print(a)

tensor([[[[-0.4981, -0.6256, -0.4970, -0.5521],
          [-0.1108,  0.7618, -1.3766,  0.8064],
          [ 1.6970, -2.0223,  0.2529, -1.0003]],

         [[-1.6542, -0.2022,  0.4417, -0.0819],
          [ 0.6332, -0.2028,  1.3380, -1.5960],
          [-0.2719,  1.0771, -0.8568, -0.5844]]]])


In [61]:
b = torch.squeeze(a)

In [62]:
print(b.shape)
print(torch.unsqueeze(b, dim=2).shape)

torch.Size([2, 3, 4])
torch.Size([2, 3, 1, 4])


In [63]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)
print(x.dim())
print(torch.unsqueeze(x, dim=1).shape)

torch.Size([4])
1
torch.Size([4, 1])


In [64]:
b = a.transpose(1,2)
print(b)

tensor([[[[-0.4981, -0.6256, -0.4970, -0.5521],
          [-1.6542, -0.2022,  0.4417, -0.0819]],

         [[-0.1108,  0.7618, -1.3766,  0.8064],
          [ 0.6332, -0.2028,  1.3380, -1.5960]],

         [[ 1.6970, -2.0223,  0.2529, -1.0003],
          [-0.2719,  1.0771, -0.8568, -0.5844]]]])


In [65]:
print(a.shape, b.shape)

torch.Size([1, 2, 3, 4]) torch.Size([1, 3, 2, 4])


In [66]:
a = torch.randn(5, 3)

In [67]:
a.view(-1,5)

tensor([[-0.1183, -0.5315,  0.3990,  1.9161,  0.0867],
        [ 1.3294, -0.4191,  0.1833,  2.6521, -1.3386],
        [-0.8111, -1.2236, -0.3969, -1.2640,  1.5572]])

In [95]:
x = torch.randn(1, 5, 3).type(torch.FloatTensor)

In [96]:
y = torch.randn(1, 5, 3)
y.type()

'torch.FloatTensor'

In [97]:
v = torch.cat([x, y], 0)

In [98]:
x.shape, y.shape, v.shape

(torch.Size([1, 5, 3]), torch.Size([1, 5, 3]), torch.Size([2, 5, 3]))

In [99]:
u = torch.stack([x, y])

In [100]:
print(x)
print(y)
print(u)
print(x.shape, y.shape, v.shape, u.shape)

tensor([[[ 0.3856, -0.6188, -0.2939],
         [-1.2614,  1.6813, -0.6430],
         [ 0.8118,  1.4205, -0.4980],
         [-0.9878, -0.6202,  0.8661],
         [-0.3967, -1.0970,  1.3531]]])
tensor([[[ 0.6429, -0.6450, -0.8904],
         [-0.5412, -0.1164,  0.1145],
         [-0.0904,  0.8527,  1.4623],
         [ 0.6218,  2.0221,  0.2533],
         [-0.1603,  0.9349,  0.2694]]])
tensor([[[[ 0.3856, -0.6188, -0.2939],
          [-1.2614,  1.6813, -0.6430],
          [ 0.8118,  1.4205, -0.4980],
          [-0.9878, -0.6202,  0.8661],
          [-0.3967, -1.0970,  1.3531]]],


        [[[ 0.6429, -0.6450, -0.8904],
          [-0.5412, -0.1164,  0.1145],
          [-0.0904,  0.8527,  1.4623],
          [ 0.6218,  2.0221,  0.2533],
          [-0.1603,  0.9349,  0.2694]]]])
torch.Size([1, 5, 3]) torch.Size([1, 5, 3]) torch.Size([2, 5, 3]) torch.Size([2, 1, 5, 3])


In [101]:
x

tensor([[[ 0.3856, -0.6188, -0.2939],
         [-1.2614,  1.6813, -0.6430],
         [ 0.8118,  1.4205, -0.4980],
         [-0.9878, -0.6202,  0.8661],
         [-0.3967, -1.0970,  1.3531]]])

In [106]:
x.max(), x.argmax()

(tensor(1.6813), tensor(4))

In [113]:
u.shape

torch.Size([2, 1, 5, 3])

In [116]:
u

tensor([[[[ 0.3856, -0.6188, -0.2939],
          [-1.2614,  1.6813, -0.6430],
          [ 0.8118,  1.4205, -0.4980],
          [-0.9878, -0.6202,  0.8661],
          [-0.3967, -1.0970,  1.3531]]],


        [[[ 0.6429, -0.6450, -0.8904],
          [-0.5412, -0.1164,  0.1145],
          [-0.0904,  0.8527,  1.4623],
          [ 0.6218,  2.0221,  0.2533],
          [-0.1603,  0.9349,  0.2694]]]])

In [121]:
u.shape

torch.Size([2, 1, 5, 3])

In [130]:
max_, ind_max = u.max(dim=0)
max_.shape

torch.Size([1, 5, 3])

In [131]:
x = torch.randn(32, 3, 5, 7)

In [133]:
max_, ind_max = x.max(dim=0)
print(max_.shape, ind_max.shape)

torch.Size([3, 5, 7]) torch.Size([3, 5, 7])


In [134]:
ind_max

tensor([[[31,  3, 30,  7, 26, 24, 27],
         [ 4, 31, 12, 10,  1, 25, 25],
         [25, 23,  4, 14, 14, 17,  5],
         [31, 12, 10, 12,  2, 24, 18],
         [25, 24,  0,  9, 30,  5,  3]],

        [[26, 27, 23, 18,  8,  4,  5],
         [ 9, 19, 13, 14, 16, 12, 27],
         [30, 17, 24, 29, 26, 20, 16],
         [ 0, 11, 30, 13,  7,  8, 20],
         [11, 10, 11, 20, 13, 20,  9]],

        [[ 8,  3, 31,  3, 26,  3,  5],
         [14,  5, 30,  3, 18,  2,  5],
         [25, 13, 14,  6, 29, 10, 10],
         [17, 10, 15, 10, 18, 30, 24],
         [12,  9, 13, 12, 21, 14,  8]]])

In [75]:
v = torch.arange(9)
v = v.view(3, 3)

In [76]:
v

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [77]:
torch.gather(v, 0, torch.LongTensor([[0,1,0],[1,2,0]]))
# the index tensor here specifies the indices of the elements needed. If 
# dim==0 (like here) the tensor specifies the row number of elements needed 
# in each of the columns, so [0,1,0] here means 1st element of 1st column, 
# 3rd element of 2nd column and 1st element of 3rd column. This implies that
# if dim==0 then index.shape[1] == input.shape[1]

# similarly if dim==1, then index.shape[0] == input.shape[0]

tensor([[0, 4, 2],
        [3, 7, 2]])

In [78]:
torch.gather(v, 1, torch.LongTensor([[0,1],[1,0],[2,1]]))

tensor([[0, 1],
        [4, 3],
        [8, 7]])

In [79]:
# output[i][j] = input[index[i][j]] [j]  #dim == 0
# output[i][j] = input[i] [index[i][j]]  #dim == 1

In [80]:
torch.chunk(v, 2)

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([[6, 7, 8]]))

In [81]:
torch.split(v, 2)

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([[6, 7, 8]]))

In [82]:
indices = torch.LongTensor([0, 2])
r = torch.index_select(v, 1, indices)
print(r)

tensor([[0, 2],
        [3, 5],
        [6, 8]])


In [83]:
v[[2,0,1],[0,2,1]]

tensor([6, 2, 4])

In [84]:
mask = v.ge(3)
r = torch.masked_select(v, mask)

In [85]:
v[v > 3]

tensor([4, 5, 6, 7, 8])

In [86]:
torch.squeeze

<function _VariableFunctions.squeeze>

In [87]:
x = torch.Tensor([1, 2, 3])
r = torch.unsqueeze(x, 0)

In [3]:
torch.cat()

TypeError: cat() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of Tensors tensors, name dim, Tensor out)
 * (tuple of Tensors tensors, int dim, Tensor out)
